### ISSUE TITLE
ユーザーカラーのαがオパシティに影響を与えていない

### ISSUE THREAD

**Issue by kyi** [effekseer/EffekseerForUE#2]
マテリアル内のUserColorパラメータのαがオパシティに影響を与えていません。
そのためフェードイン、フェードアウトが有効化されていません。

手元で変更してみたところmultiplyすることで目的の結果になりました。
確認したのはM_TranslucentのみですがAdditiveのほうでも同様のことが起こると思います。
よろしくお願いします。

**Comment by effekseer** [comment]
報告ありがとうございます。
週末あたりに確認してみます。

**Comment by effekseer** [comment]
修正しましたがこれでどうでしょうか？

https://github.com/effekseer/EffekseerForUE4/commit/84a1e3d96637ed2223abaa9e8ead3b295deb3a02

**Comment by kyi** [comment]
@effekseer 修正されていることを確認しました。
対応ありがとうございます。
